swagger: '2.0'
info:
  description: crypto-coins api
  title: Swagger backend Def
  version: 1.0.0
host: carlosalbertogodoy.ddns.net
schemes:
  - https
basePath: /
paths:
  /coins:
    get:
      summary: Get Initial crypto-coins prices
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  timestamp:
                    type: string
                  error_code:
                    type: number
                  error_message:
                    type: string
                  elapsed:
                    type: number
                  credit_count:
                    type: number
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    price:
                      type: number
  /coins/{coinId}:
    get:
      tags:
        - coin
      summary: Find coin by ID
      description: Returns a single coin
      operationId: getCoinById
      parameters:
        - name: coinId
          in: path
          description: ID of coin to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: succesful operation
          schema:
            $ref: '#/definitions/Coin'
definitions:
  Coin:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      price:
        type: integer
        format: int64
    xml:
      name: Coin/autenticar
/graphql
/api
/api/users
/courses
/courses
/api/initportada
/api/portada
/api/actualizar
/api/insertar
/api/countries
/files
/
/*
