openapi: 3.0.0
info:
  title: curseitor api
  version: 1.0.0
tags:
- name: curseitor
  description: courses, lessons and users
servers:
  - url: https://carlosalbertogodoy.ddns.net/api    # The "url: " prefix is required
paths:
  /users:
    get:
        summary: Get users
        responses:
          '200':
            description: Success response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
  /coins/names/{coinName}:
    get:
      tags:
        - coin
      summary: Find coin by Name
      description: Returns a single coin
      operationId: getCoinByName
      parameters:
        - name: coinName
          in: path
          description: Name of coin to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
            application/xml:
              schema:
                $ref: '#/components/schemas/Price'
  /coins/ids/{coinId}:
    get:
      tags:
        - coin
      summary: Find coin by ID
      description: Returns a single coin
      operationId: getCoinById
      parameters:
        - name: coinId
          in: path
          description: ID of coin to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coin'
            application/xml:
              schema:
                $ref: '#/components/schemas/Coin'
  /coins/history/{coinName}:
    get:
      tags:
        - history
      summary: Retrieve history of one crypto-coin
      description: Return a json with the history of the named cripto-coin
      operationId: getHistoryByName
      parameters:
        - name: coinName
          in: path
          description: Name of crypto-coin
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICoinHistory'
components:
  schemas:
    ICoinHistory:
      type: object
      properties:
        name:
          type: string
        timePriceArray:
          type: array
          items:
            type: object
            properties:
              price:
                type: number
              timestamp:
                type: string
                format: date
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: User
    Price:
      type: number
    ICoinsResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            timestamp:
              type: string
            error_code:
              type: number
            error_message:
              type: string
            elapsed:
              type: number
            credit_count:
              type: number
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              price:
                type: number
